print("Getting to know you!")

name = input("What's your name?")
food = input("What's your favourite fodd:")
music =  input("What's your favourite music?")
living = input("Where do you live?:")

print("You are")
print(name)
print()
print("You probabably hungry for")
print(food)
print()
print("and you're definitely getting your groove on to")
print( music)
print()
print("living in the amazing")
print(living)
print()
print("Have a great day!")